[package]
name = "ansirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ansirs"
path = "src/lib.rs"

[[bin]]
name = "ansitest"
path = "src/bin/bin.rs"

[dependencies]
unicode-width = "0.1.7"
